title: Jorge Israel Frómeta Moya
logo: images/self-modified.png
description: Portafolio de Jorge Israel Frómeta, ingeniero industrial con más de 10 años de experiencia en optimización logística y productiva. Especializado en análisis de datos, programación en Python, Power BI, SQL, y modelos matemáticos para la gestión de cadenas de suministro y ruteo vehicular. Certificado en Análisis de Datos (Google) y Ciencia de Datos (IBM), con amplia experiencia docente y en consultoría empresarial.
show_downloads: true
theme: jekyll-theme-merlot
